title: The code zone
author: Jan Morgenstern
email: janmorgensternnls@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where I live

# social links
twitter_username: janmorgen # DO NOT include the @ character, or else the build will fail!
github_username:  Janmorgen # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
